CREATE TABLE SMPF_BUDGET
(
  BUDG_YYMM            TEXT     NOT NULL,
  CODE_TYPE            INTEGER  NULL,
  DEPTH1_CODE          INTEGER  NULL,
  DEPTH2_CODE          INTEGER  NULL,
  BUDG_AMT             NUMERIC  NULL,
  PRIMARY KEY (BUDG_YYMM, CODE_TYPE, DEPTH1_CODE, DEPTH2_CODE)
);

CREATE TABLE SMPF_CODE (
  CODE_TYPE     INTEGER   NOT NULL, 
  DEPTH1_CODE   INTEGER   NOT NULL, 
  DEPTH2_CODE   INTEGER   NOT NULL    DEFAULT 0, 
  CODE_NAME     TEXT      NOT NULL, 
  LICON_NAME    TEXT, 
  SICON_NAME    TEXT, 
  INCOME_TYPE   INTEGER, 
  DEFAULT_YN    TEXT      NOT NULL    DEFAULT 'N', 
  CODE_LEVEL    INTEGER, 
  ORDER_SEQ     INTEGER,
  USE_YN        TEXT      NOT NULL    DEFAULT 'Y', 
  PRIMARY KEY (CODE_TYPE, DEPTH1_CODE, DEPTH2_CODE)
);

CREATE TABLE SMPF_CONF
(
  BUDG_DAY             TEXT     NOT NULL,
  CAL_TYPE             TEXT     NOT NULL,
  HB_TYPE              TEXT     NOT NULL,
  PRIMARY KEY (BUDG_DAY)
);

CREATE TABLE SMPF_DBVER
(
  DB_VER               TEXT     NOT NULL,
  UPDATE_DAY           TEXT     NULL,
  PRIMARY KEY (DB_VER)
);

CREATE TABLE SMPF_HOLIDAY
(
  HD_DT                TEXT     NOT NULL,
  HD_NM                TEXT     NULL,
  USE_YN               TEXT     NOT NULL  DEFAULT 'Y',
  PRIMARY KEY (HD_DT)
);

CREATE TABLE SMPF_INCOME (
  INCOME_SEQ      INTEGER   NOT NULL, 
  INCOME_DATE     TEXT      NOT NULL, 
  CODE_TYPE       INTEGER   NOT NULL, 
  DEPTH1_CODE     INTEGER   NOT NULL, 
  DEPTH2_CODE     INTEGER   NOT NULL, 
  INCOME_AMT      NUMERIC   NOT NULL    DEFAULT 0, 
  INCOME_MEMO     TEXT, 
  INCOME_TYPE1    INTEGER, 
  INCOME_TYPE2    INTEGER, 
  REPEAT_TYPE     INTEGER, 
  REPEAT_DAY      TEXT, 
  REPEAT_START    TEXT, 
  REPEAT_END      TEXT,
  ORG_SEQ         INTEGER, 
  PHOTO_NAME      TEXT, 
  MAP_LATITUDE    TEXT, 
  MAP_LONGITUDE   TEXT, 
  MAP_ADDR        TEXT,
  PRIMARY KEY (INCOME_SEQ)
);
